format = """\
[ ](fg:#fe8019)\
$username\
$hostname\
$localip\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$dotnet\
$golang\
$guix_shell\
$helm\
$lua\
$nim\
$nodejs\
$ocaml\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$nix_shell\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character\
"""

[directory]
format = "[ ﱮ $path ]($style)"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "

[git_status]
format = '[$all_status]($style) '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_metrics]
format = "([+$added]($added_style))"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
disabled = false
format = "[  $duration ]($style)"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#cc241d) '

[time]
disabled = false
use_12hr = true

[localip]
ssh_only = false
format = '@ [$localipv4](bold blue) '
disabled = false

[line_break]
disabled = true