format = """\
[](bg:#282828 fg:#282828)\
[ ](bg:#282828 fg:#fe8019)\
[](fg:#282828 bg:#928374)\
$time\
[](fg:#928374 bg:#458588)\
$directory\
[](fg:#458588 bg:#98971a)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#98971a bg:#282828)\
$character\
"""

[directory]
format = "[ ﱮ $path ]($style)"
style = "fg:#ebdbb2 bg:#458588"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#98971a"

[git_status]
format = '[$all_status]($style)'
style = "fg:#98971a bg:#98971a"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#98971a"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#cc241d) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#928374"
format = '[[ 󱑍 $time ](bg:#928374 fg:#282828)]($style)'
